CREATE TABLE garment_products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    brand VARCHAR(50),
    size VARCHAR(10),
    color VARCHAR(30),
    base_price NUMERIC(10,2)
);

INSERT INTO garment_products
SELECT
    id AS product_id,
    'Product_' || id AS product_name,
    CASE WHEN id % 5 = 0 THEN 'Jeans'
         WHEN id % 5 = 1 THEN 'T-Shirt'
         WHEN id % 5 = 2 THEN 'Shirt'
         WHEN id % 5 = 3 THEN 'Jacket'
         ELSE 'Dress' END AS category,
    CASE WHEN id % 4 = 0 THEN 'Nike'
         WHEN id % 4 = 1 THEN 'Zara'
         WHEN id % 4 = 2 THEN 'H&M'
         ELSE 'Adidas' END AS brand,
    CASE WHEN id % 3 = 0 THEN 'S'
         WHEN id % 3 = 1 THEN 'M'
         ELSE 'L' END AS size,
    CASE WHEN id % 4 = 0 THEN 'Black'
         WHEN id % 4 = 1 THEN 'White'
         WHEN id % 4 = 2 THEN 'Blue'
         ELSE 'Red' END AS color,
    ROUND((50 + RANDOM() * 150)::numeric, 2) AS base_price
FROM generate_series(1, 200) id;


CREATE TABLE garment_sales (
    sale_id INT PRIMARY KEY,
    product_id INT,
    sale_date DATE,
    quantity INT,
    discount_percent NUMERIC(5,2),
    total_amount NUMERIC(12,2),
    store_city VARCHAR(50),
    FOREIGN KEY (product_id) REFERENCES garment_products(product_id)
);



INSERT INTO garment_sales
SELECT
    id AS sale_id,
    (RANDOM() * 199 + 1)::INT AS product_id,
    DATE '2024-01-01' + (RANDOM() * 180)::INT AS sale_date,
    (RANDOM() * 5 + 1)::INT AS quantity,
    ROUND((RANDOM() * 30)::numeric, 2) AS discount_percent,
    ROUND((200 + RANDOM() * 800)::numeric, 2) AS total_amount,
    CASE WHEN id % 5 = 0 THEN 'New York'
         WHEN id % 5 = 1 THEN 'London'
         WHEN id % 5 = 2 THEN 'Berlin'
         WHEN id % 5 = 3 THEN 'Tokyo'
         ELSE 'Sydney' END AS store_city
FROM generate_series(1, 200) id;

select * from garment_products;

select * from garment_sales;



--🟢 BASIC LEVEL (1–10)

select * from garment_sales;


--What are the different garment categories present?

select distinct category
from garment_products;


--List all products that belong to a specific brand (e.g., Nike).

select * from garment_products
where brand = 'Nike';

--What is the average base price of all garments?

select avg(base_price)
from garment_products;

--How many sales transactions have been recorded?

select sum(quantity)
from garment_sales;

--6. Total sales quantity

select sum(quantity) as sales_quantity
from garment_sales;

--7. List all store cities

select distinct store_city
from garment_sales;

--How many products are available in each size (S, M, L)?

select size, count(*)
from garment_products
group by size;

--Find all garments priced above a certain amount.
SELECT *
FROM garment_products
WHERE base_price > 50;



--Retrieve all sales records for a specific product.

SELECT *
FROM garment_sales
WHERE product_id = 105;


--🟡 INTERMEDIATE LEVEL (11–20)

--What is the total sales revenue generated across all stores?

select sum(total_amount) as total_revenue
from garment_sales;


--How much total revenue was generated by each garment category?

select p.category, sum(s.total_amount) as total_revenue
from garment_products p
join
garment_sales s
on p.product_id = s.product_id
group by p.category;

--Which products have sold the highest total quantity?

select p.product_name, sum(s.quantity) as highest_quantity
from garment_products p
join
garment_sales s
on p.product_id = s.product_id
group by p.product_name
order by highest_quantity desc;


--What is the total revenue generated by each brand?

select p.brand, sum(s.total_amount) as total_revenue
from garment_products p
join
garment_sales s
on p.product_id = s.product_id
group by p.brand;


--Which products have never been sold?

SELECT p.product_id, p.product_name
FROM garment_products p
LEFT JOIN garment_sales s ON p.product_id = s.product_id
WHERE s.product_id IS NULL;


--What is the average discount applied across all sales?

SELECT AVG(discount_percent) AS avg_discount
FROM garment_sales;


--What is the daily sales trend over time?

select sale_date, sum(total_amount) as daily_revenue
from garment_sales
group by sale_date
order by sale_date;

---Which product generated the highest revenue overall?

select p.product_id, product_name, sum(s.total_amount) as highest_revenue
from garment_products p
join
garment_sales s
on p.product_id = s.product_id
group by p.product_id, p.product_name
order by highest_revenue desc limit 1;

--🔴 ADVANCED LEVEL (21–30)

--Rank products by total revenue using window functions.
SELECT p.product_name,
       SUM(total_amount) AS revenue,
       RANK() OVER (ORDER BY SUM(total_amount) DESC) AS revenue_rank
FROM garment_sales s
JOIN garment_products p ON s.product_id = p.product_id
GROUP BY product_name;



---What percentage of total revenue is contributed by each category?
SELECT p.category,
       SUM(s.total_amount) AS category_revenue,
       100.0 * SUM(s.total_amount) / SUM(SUM(s.total_amount)) OVER () AS percentage
FROM garment_sales s
JOIN garment_products p ON s.product_id = p.product_id
GROUP BY p.category;



--Calculate a moving average of daily sales revenue.

SELECT sale_date,
       SUM(total_amount) AS daily_revenue,
       AVG(SUM(total_amount)) OVER (
           ORDER BY sale_date
           ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
       ) AS moving_avg_7_days
FROM garment_sales
GROUP BY sale_date
ORDER BY sale_date;


---Detect sales transactions that have unusually high discounts.
SELECT *
FROM garment_sales
WHERE discount_percent > (
    SELECT AVG(discount_percent) + 2 * STDDEV(discount_percent)
    FROM garment_sales
);



--Which brand is the most profitable based on total revenue?
SELECT p.brand, SUM(s.total_amount) AS revenue
FROM garment_sales s
JOIN garment_products p ON s.product_id = p.product_id
GROUP BY p.brand
ORDER BY revenue DESC
FETCH FIRST 1 ROW ONLY;



--Analyze monthly revenue growth trends.
SELECT DATE_TRUNC('month', sale_date) AS month,
       SUM(total_amount) AS monthly_revenue,
       LAG(SUM(total_amount)) OVER (ORDER BY DATE_TRUNC('month', sale_date)) AS prev_month_revenue
FROM garment_sales
GROUP BY DATE_TRUNC('month', sale_date)
ORDER BY month;



--Find the top-performing product within each category.
WITH category_sales AS (
    SELECT p.category,
           p.product_name,
           SUM(s.total_amount) AS revenue
    FROM garment_sales s
    JOIN garment_products p ON s.product_id = p.product_id
    GROUP BY p.category, p.product_name
)
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY category ORDER BY revenue DESC) AS rnk
    FROM category_sales
) ranked
WHERE rnk = 1;
